import unittest
from api import amiibo
from domain.models.amiibo import AmiiboCharacter, GameSeries
from .mock_data import (
    create_character_series_data,
    create_game_series_data,
    create_single_character_data
)

class TestCommands(unittest.TestCase):
    '''testing shell.commands, this is not  generated by me
       no need to test a lot just make sure the data is
     being pulldown commands should be the real test'''
    
    



    def test_get_amiibo_series(self):
        res = amiibo.get_amiibo_series();
        self.assertEqual(res,self.SERIES_DATA)
    
    def test_get_amiibo_single_series(self):
        code = "0x010" #Zelda series
        res = amiibo.get_amiibo_single_series(code);
        self.assertEqual(res,self.ZELDA_SERIES)
    
    def test_get_amiibo_single_character(self):
        code = "0x1996" #Mewtwo
        res = amiibo.get_amiibo_single(code);
        self.assertEqual(res, self.AMIIBO_MEWTWO)
        self.assertEqual(res[0].name,"Mewtwo")

    #setup
    @classmethod
    def setUpClass(self) -> None:
        print('preparing amiibo api test')
        self.SERIES_DATA = create_game_series_data()
        self.AMIIBO_MEWTWO = create_single_character_data()
        self.ZELDA_SERIES = create_character_series_data()
        
    
    @classmethod
    def tearDownClass(self) -> None:
        print('cleaning amiibo api test')

if __name__ == '__main__':
    unittest.main()