import unittest
from api import amiibo
from domain.models.amiibo import AmiiboCharacter, GameSeries

class TestCommands(unittest.TestCase):
    '''testing shell.commands, this is not  generated by me
       no need to test a lot just make sure the data is
     being pulldown commands should be the real test'''
    
    @classmethod
    def setUpClass(self) -> None:
        print('preparing  amiibo api test')
    
    @classmethod
    def tearDownClass(self) -> None:
        print('cleaning amiibo api test')


    def test_get_amiibo_series(self):
        res = amiibo.get_amiibo_series();
        self.assertIsNot(res,[])
    
    def test_get_amiibo_single_series(self):
        code = "0x010" #Zelda series
        res = amiibo.get_amiibo_single_series(code);
        self.assertIsNot(res,[])
    
    def test_get_amiibo_single_series(self):
        code = "0x1996" #Mewtwo
        res = amiibo.get_amiibo_single(code);
        self.assertIsNot(res,[])
        print(res)
        self.assertEquals(res.name,"Mewtwo")

if __name__ == '__main__':
    unittest.main()